version: '3'

services:
  php:
    container_name: whoisproxy_api
    image: php73-with-dnsutils
    build: docker/php
    restart: always
    ports:
      - "8000:80"
    volumes:
      - "./www:/var/www/html"
      - "./docker/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf"
    environment:
      TZ: Asia/Tokyo

  redis:
    container_name: whoisproxy_api_redis
    image: redis:latest
    ports:
      - "63790:6379"
